### ISSUE TITLE
Mysterious errors when using a template from a class with macros

### ISSUE THREAD

**Issue by j-jzk** [haxetink/tink_template#22]
Compilation fails with weird error messages when you try to use a template from a class which contains macros.

Consider a structure like this:
```haxe
// Main.hx
class Main {
    public static function main() {
        trace(Templ.render());
        trace(getNull());
    }

    public static macro function getNull() {
        return macro null;
    }
}
```
```
(:* Templ.tt *:)
(: public static function render() :)
    Hello
(: end :)
```

Trying to compile this results in a stream of nonsensical errors:
```
Main.hx:3: characters 15-20 : Type not found : Templ
.../haxelib/tink_syntaxhub/0,4,3/src/tink/SyntaxHub.hx:30: characters 5-89 : Build failure
.../haxe/std/haxe/io/Input.hx:32: lines 32-331 : Defined in this class
.../haxelib/tink_syntaxhub/0,4,3/src/tink/SyntaxHub.hx:30: characters 5-89 : Build failure
.../haxe/std/haxe/io/Input.hx:32: lines 32-331 : Defined in this class
.../haxe/std/haxe/io/Input.hx:164: characters 13-30 : haxe.io.BytesBuffer does not have a constructor
.../haxe/std/haxe/io/Input.hx:177: characters 13-30 : haxe.io.BytesBuffer does not have a constructor
.../haxe/std/haxe/io/Input.hx:185: characters 5-24 : Unknown<0> should be {+ substr : (Int, Int) -> Unknown<0>, length : Int, charCodeAt : Int -> Int }
.../haxe/std/haxe/io/Input.hx:191: characters 3-11 : {+ substr : (Int, Int) -> Unknown<0>, length : Int, charCodeAt : Int -> Int } should be String
.../haxelib/tink_syntaxhub/0,4,3/src/tink/SyntaxHub.hx:30: characters 5-89 : Build failure
.../haxe/std/neko/_std/haxe/ds/StringMap.hx:25: lines 25-93 : Defined in this class
.../haxelib/tink_syntaxhub/0,4,3/src/tink/SyntaxHub.hx:30: characters 5-89 : Build failure
.../haxe/std/neko/_std/haxe/ds/StringMap.hx:25: lines 25-93 : Defined in this class
.../haxelib/tink_syntaxhub/0,4,3/src/tink/SyntaxHub.hx:30: characters 5-89 : Build failure
```
(the errors even vary between compilation targets, the listing above is for neko)

If you comment out the `getNull()` call, they all disappear, with only one lonely `Type not found : Templ` being left.

Moving the macro into a separate file makes it work, but that seems as more of a quick fix rather than actually solving the issue.

**Comment by back2dos** [comment]
Sorry, there's nothing we can do here.

The way that pure template classes work (those that don't have a corresponding .hx file) is by `Context.onTypeNotFound` which is not available in macro context.

> Moving the macro into a separate file makes it work, but that seems as more of a quick fix rather than actually solving the issue.

Haxe has two distinct contexts each with its own classes/enums/etc, One hosts the code that is meant to be generated as compiler output (target context) and one hosts the code that contains the macros and runs on the interpreter. The latter one has very strong limitations for macros.

It is therefore a good practice to separate macro and non-macro code. This can be done with `#if macro` or by putting macro code into non-macro files. The above code would thus look like this:

```haxe
// Main.hx
class Main {
    static function main() {
        trace(Templ.render());
        trace(getNull());
    }

    static macro function getNull();
}
// Main.macro.hx
class Main {
    static function main() {
        trace(Templ.render());
        trace(getNull());
    }

    static function getNull() {
        return macro null;
    }
}
```

Here's the interesting thing to note: a macro exists in the target context only as an empty function with a `macro` modifier and when the compiler sees a call to a macro, it loads up the correspondent class from the macro context and class the method with the same name on it (passing any arguments as expressions rather than values) and then processes the returned expression. However, the way your above code is written `Main.main` also makes it into the macro context, where it fails, because it makes reference to `Templ`, that cannot be resolved in macro context.

Your choices are to:

1. separate your code the way that you did
2. Use fencing:

   ```haxe
   class Main {
       #if !macro
       static function main() {
           trace(Templ.render());
           trace(getNull());
       }
       #end
   
       static macro function getNull()
           return macro null;
   }
   ```
3. Put only the right code into the .macro.hx file:

   ```haxe
   // Main.hx
   class Main {
       static function main() {
           trace(Templ.render());
           trace(getNull());
       }
       macro static function getNull();
   }
   // Main.macro.hx
   class Main {
        static function getNull()
            return macro null;
   }
```
